version: '3.8'

services:
  nginx:
    container_name: nginx_container
    build:
      context: ./srcs/requirements/nginx
    ports:
      - "443:443"
    environment:
      - NGINX_SSL_CERTIFICATE=${NGINX_SSL_CERTIFICATE}
      - NGINX_SSL_CERTIFICATE_KEY=${NGINX_SSL_CERTIFICATE_KEY}
    volumes:
      - ./srcs/requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/requirements/nginx/ssl:/etc/nginx/ssl
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception_network
    # restart: on-failure
    restart: "no"

  mariadb:
    container_name: mariadb_container
    build:
      context: ./srcs/requirements/mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    user: mysql
    # restart: unless-stopped
    restart: "no"
    #healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #  interval: 20s
    #  retries: 10
    #  timeout: 5s
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$(cat /run/secrets/db_root_password)"]
    #   interval: 30s
    #   retries: 10
    #   timeout: 5s
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-uroot", "--socket=/var/run/mysqld/mysqld.sock"]
    #   interval: 30s
    #   retries: 10
    #   timeout: 5s
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-uroot", "-p$(cat /run/secrets/db_root_password)", "--socket=/var/run/mysqld/mysqld.sock"]
    #   interval: 30s
    #   retries: 10
    #   timeout: 5s

    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-uroot", "-p$(< /run/secrets/db_root_password)", "--socket=/var/run/mysqld/mysqld.sock"]
    #   interval: 30s
    #   retries: 10
    #   timeout: 5s

    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping -uroot -p\"$(cat /run/secrets/db_root_password)\" --silent || exit 1"]
    #   interval: 30s
    #   retries: 10
    #   timeout: 5s

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$(cat /run/secrets/db_root_password) --silent || exit 1"]
      interval: 30s
      retries: 10
      timeout: 5s




  wordpress:
    container_name: wordpress_container
    build:
      context: ./srcs/requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    secrets:
      - db_password
    volumes:
      - wordpress_data:/var/www/html
      - ./srcs/requirements/wordpress/conf/wp-config.php:/var/www/html/wp-config.php
    security_opt:
      - seccomp:unconfined
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception_network
    #restart: unless-stopped # a remettre
    restart: "no"
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost"]
    #  interval: 30s
    #  retries: 5
    #  timeout: 10s
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://nginx_container"]
    #  interval: 30s
    #  retries: 5
    #  timeout: 10s
    #healthcheck:
    #  test: ["CMD-SHELL", "curl -f http://localhost/wp-login.php || exit 1"]
    #  interval: 30s
    #  retries: 5
    #  timeout: 10s
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/wp-login.php || exit 1"]
      interval: 30s
      retries: 5
      timeout: 10s




secrets:
  db_password:
    file: ./srcs/requirements/mariadb/secrets/db_password.txt
  db_root_password:
    file: ./srcs/requirements/mariadb/secrets/db_root_password.txt


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alex/42cursus/inception/data/db_data


  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alex/42cursus/inception/data/wp_data

networks:
  inception_network:
    driver: bridge
