services:
  php:
    container_name: librairie-php
    build:
      context: /Users/alex/docker-php-sqlsrv
      dockerfile: Dockerfile
    image: php-sqlsrv:8.3.17
    volumes:
      - ./:/srv/app
    working_dir: /srv/app
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sql_edge_container
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - librairie_mssql_data:/var/opt/mssql
    restart: always
    networks:
      - librairie-network

volumes:
  librairie_mssql_data:
    driver: local

networks:
  librairie-network:
    driver: bridge
