services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: shared_db_user
      POSTGRES_PASSWORD: deplanta1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shared_db_user -d user_service_db"]
      interval: 5s
      retries: 5
    networks:
      - app_network

  user_service:
    build:
      context: ./user-service
    ports:
      - "8080:8080" # Mappage du port local 8081 vers le port 8000 du conteneur
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: user_service_db
      POSTGRES_USER: shared_db_user
      POSTGRES_PASSWORD: deplanta1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./user-service:/usr/src/app/user-service
      - ./user-service/logs:/usr/src/app/logs

  matchtracker_service:
    build:
      context: ./matchtracker-service
    ports:
      - "8000:8000"  # Mappage du port local 8082 vers le port 8000 du conteneur
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: matchtracker_service_db
      POSTGRES_USER: shared_db_user
      POSTGRES_PASSWORD: deplanta1
      USER_SERVICE_URL: http://user_service:8080/api/user
    depends_on:
      postgres:
        condition: service_healthy
      user_service:
        condition: service_started
    networks:
      - app_network
    volumes:
      - ./matchtracker-service:/usr/src/app/matchtracker-service
      - ./matchtracker-service/logs:/usr/src/app/logs

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
