services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: shared_db_user
      POSTGRES_PASSWORD: deplanta1
      POSTGRES_DB: user_service_db  # La base de données par défaut, d'autres peuvent être créées
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shared_db_user"]
      interval: 5s
      retries: 5

  user_service:
    build:
      context: ./user-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: user_service_db
      POSTGRES_USER: shared_db_user
      POSTGRES_PASSWORD: deplanta1
    depends_on:
      postgres:
        condition: service_healthy

  matchtracker_service:
    build:
      context: ./matchtracker-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: matchtracker_service_db
      POSTGRES_USER: shared_db_user
      POSTGRES_PASSWORD: deplanta1
    depends_on:
      - postgres

volumes:
  postgres_data:
