# Generated by Django 5.1.4 on 2024-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_tournament_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pong_game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.JSONField(default=list),
        ),
    ]
