# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: astutz <alex.rastafari@hotmail.com>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/22 14:44:25 by jseo              #+#    #+#              #
#    Updated: 2022/10/26 15:53:25 by astutz           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)
FLAGS = -Wall -Wextra -Werror -std=c99



# $(NAME)		:	$(OBJS)
# 			gcc $(FLAGS) -c $(SRCS) -I./
# 			ar rc $(NAME) $(OBJS)

# libft.a		:	SRCS:%.c=%.o
# 			gcc $(FLAGS) -c $(SRCS) -I./

# all	:	$(NAME)

# bonus	:	$(NAME)
# 		gcc $(FLAGS) -c $(BNS_SRCS) -I./
# 		ar rc $(NAME) $(BNS_OBJS)

# clean	:
# 		rm -f $(OBJS) $(BNS_OBJS)

# fclean	:	clean
# 		rm -f $(NAME)

# re	:	fclean all

# .PHONY	:	all clean fclean re